apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emlo-s23-cluster
  region: us-west-2
  version: "1.28"
  # tags:
  #   - kubernetes.io/cluster/emlo-s23-cluster: "shared"

iam:
  withOIDC: true

vpc:
  id: vpc-0b4241f730b340531
  subnets:
    public:
      us-west-2a:
        id: "subnet-0a11af0a1aa1b1541"
      us-west-2b:
        id: "subnet-01b6885c030a95bf5"
      us-west-2c:
        id: "subnet-0e7c6e3052e92ccd3"

managedNodeGroups:
  - name: ng-cpu-spot-1
    instanceType: t3a.2xlarge
    volumeSize: 60
    volumeType: gp3
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyPath: /home/ubuntu/.ssh/id_rsa.pub
    spot: true
    labels:
      role: spot
    iam:
      withAddonPolicies:
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        externalDNS: true
        ebs: true
