apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: models
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mmgxa/argo
    targetRevision: HEAD
    path: models
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
